In [4]:
# 1차원 배열
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

print(np.ndim(a))
print(a.shape)
print(a.shape[0])

[1 2 3 4 5]
1
(5,)
5


In [8]:
# 2차원 배열
import numpy as np

b = np.array([[1,2],[3,4],[5,6]])
print(b)

print(np.ndim(b)) # 몇차원인지 출력
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [12]:
# 행렬 연산 2*2

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print("a : ",a.shape)
print("b : ",b.shape)

print('a,b : ',np.dot(a,b))
print('b,a : ',np.dot(b,a))

a :  (2, 2)
b :  (2, 2)
a,b :  [[19 22]
 [43 50]]
b,a :  [[23 34]
 [31 46]]


In [15]:
# 3*2, 2*3

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
print(b.shape)

print('a,b : ',np.dot(a,b))
print('b,a : ',np.dot(b,a))

(2, 3)
(3, 2)
a,b :  [[22 28]
 [49 64]]
b,a :  [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [3]:
import numpy as np

# 행렬의 형상 에러


a = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2],[3,4]])
print(c.shape)
print(a.shape)
np.dot(a,c)

(2, 2)
(2, 3)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [6]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
b = np.array([[7,8,9,10],[11,12,13,14]])
print(b.shape)

print(np.dot(a,b))

(3, 2)
(2, 4)
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]
