In [6]:
# 신경망에서의 기울기

import sys,os
sys.path.append(os.pardir)
import numpy as np
from functions import softmax, cross_entropy_error
from gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3) # 정규분포로 초기화
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss
    
net = simpleNet()
print(net.W) # 가중치 매개변수


x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

np.argmax(p) # 최대값의 인덱스

t = np.array([0, 0 , 1]) #  정답 레이블
print(net.loss(x, t))


def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

# lambda 기법

f = lambda w : net.loss(x, t)
dW = numerical_gradient(f, net.W)

[[-1.15489019 -0.47222778 -1.57250635]
 [-2.1555243  -2.8095467   0.96038844]]
[-2.63290598 -2.8119287  -0.07915421]
0.1335056564283909
[[ 0.04084041  0.03414613 -0.07498654]
 [ 0.06126061  0.0512192  -0.11247981]]
