In [1]:
import numpy as np

## zeros & ones

0으로 채워진 numpy array 만들기


In [7]:
zeros = np.zeros([3, 3]) # 0으로 3,3 배열이 생성

print("np.zeros([3,3]): ",zeros)

np.zeros([3,3]):  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
zeros = np.zeros(1)
print(zeros)

[0.]


In [10]:
ones = np.ones([10, 5]) # 1로 10행 5열 생성
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
print(ones * 5)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [14]:
arr = np.arange(5)
print(arr) # 0부터 4까지

[0 1 2 3 4]


In [15]:
arr2 = np.arange(4, 9)
print(arr2) # 4부터 9전까지 8


[4 5 6 7 8]


In [17]:
arr3 = np.arange(10, 20)
print(arr3)


[10 11 12 13 14 15 16 17 18 19]


In [19]:
arr = np.arange(9).reshape(3,3) # 0~8을 reshape를 통해서 3,3으로 2차원 배열 변경
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Index


In [22]:
nums = [1,2,3,4,5]

nums[2:] # 두번째 위치 3 부터 전부

[3, 4, 5]

In [26]:
nums = [1,2,3,4,[1,2,3]]

print(nums)
print(nums[4])

[1, 2, 3, 4, [1, 2, 3]]
[1, 2, 3]


# Slicing

In [27]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr[1:] # 1부터 전부 3,4,5 배열 하나, 6,7,8 

array([[3, 4, 5],
       [6, 7, 8]])

In [31]:
print(arr[1:, 1:]) # 4,5, 7,8 두개씩

[[4 5]
 [7 8]]


# Boolean Indexing

In [39]:
data = np.random.rand(3, 3)  #3행 3열 2차원 배열 랜덤 숫자 
data

array([[0.44816848, 0.2410303 , 0.78655282],
       [0.22368746, 0.07653967, 0.94830356],
       [0.89653982, 0.16857122, 0.75203086]])

In [40]:
print(data <= 0) # 0보다 작은 것 

[[False False False]
 [False False False]
 [False False False]]


In [41]:
data[data <=0] = 1

data

array([[0.44816848, 0.2410303 , 0.78655282],
       [0.22368746, 0.07653967, 0.94830356],
       [0.89653982, 0.16857122, 0.75203086]])

# Boradcast

tensorflow나 pytorch 계산시 broadcast 개념 이해해야 한다.

broadcast는 연산하려는 서로 다른 두 개의 행렬의 shape가 같지 않고,
한쪽의 차원이라도 같거나 또는 값의 개수가 한 개 일때
이를 여러 복사를 해 연산을 한다.

In [44]:
arr = np.arange(9).reshape(3, 3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
arr + 3 # 3씩 더함

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
arr * 3 # 각 3씩 곱하기

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [47]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr + np.array([1,2,3]) # 1,2,3씩 더함

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [51]:
np.sum(arr) # 전부 더하기

36

In [53]:
np.max(arr) # 최대값 출력

8

In [55]:
np.mean(arr) # 평균

4.0

In [56]:
arr_2 = np.array([1,6,3,4,6,8,12,4])
arr_2


array([ 1,  6,  3,  4,  6,  8, 12,  4])

In [58]:
np.argmax(arr_2) # 최대값의 위치 index


6

In [59]:
np.argmin(arr_2) # 최소값의 위치 index


0

In [60]:
arr_3 = np.array([3,5,6,7,7,3,3,1])
arr_3


array([3, 5, 6, 7, 7, 3, 3, 1])

In [61]:
np.unique(arr_3) # 중복제거해서 작은 수부터 출력해준다.


array([1, 3, 5, 6, 7])

# Numpy Basic



In [65]:
# data type

arr4 = np.array([[1,2,3],[1,2,3]])
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
arr.dtype # inte 32 데이터 타입

dtype('int32')

In [71]:
arr2 = arr.astype(np.float32) # float 32형으로 변경
arr2.dtype # arr2 타입 변경

dtype('float32')

In [74]:
# 혹은 처음부터 설정 가능하다.

arr3 = np.array([[1,2,3],[1,2,3]], dtype=np.float32)
arr3.dtype

dtype('float32')

In [76]:
len(arr3.shape) # 2차원 확인

2

In [77]:
arr3.shape # 2행 3열

(2, 3)

In [78]:
arr3.size # 총 6공간 2 * 3

6

# Reshape
사이즈는 그대로 유지하고 모양을 바꿈- 차원

In [82]:
arr3 = arr3.reshape([1,6])
arr3.shape

(1, 6)

In [83]:
arr3 = np.array([[1,2,3],[1,2,3]])
ar r3.reshape([6]).shape

(6,)