In [4]:
# 편향과 활성화 함수를 생략하고 가중치만 갖는 신경망

import numpy as np

x = np.array([1,2])
print(x.shape)

w = np.array([[1,3,5],[2,4,6]])
print(w)
print(w.shape)

y = np.dot(x,w)
print(y)


(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]


In [14]:
# 3층 신경망 

import numpy as np

x = np.array([1.0,0.5])
w1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
b1 = np.array([0.1,0.2,0.3])

print(w1.shape)
print(x.shape)
print(b1.shape)

A1 = np.dot(x,w1) + b1 # 구현 식
print(A)

def sigmoid(x):
    return 1/(1+np.exp(-x)) # 시그모이드 수식

z1 = sigmoid(A1)

print(A1)
print(z1)


W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])

print(z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(z1,W2)+ B2
Z2 = sigmoid(A2)
print(A2)
print(Z2)


def identity_function(x):
    return x

W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2,W3)+B3

Y = identity_function(A3) # 혹은 Y = A3
print(Y)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]
(3,)
(3, 2)
(2,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]
[0.31682708 0.69627909]


In [15]:
import numpy as np


def sigmoid(x):
    return 1/(1+np.exp(-x)) # 시그모이드 수식

def identity_function(x):
    return x

def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    
    return network


def forward(network,x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

network = init_network()
x = np.array([1.0,0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
